# The parameter "input" and "output" are the absolute path. Do not include the "/" at the end of the paths.
input          : "/blue/bphl-florida/dongyibo/Dev_module_Talbot/gffs"
output    : "/blue/bphl-florida/dongyibo/Dev_module_Talbot/output"

# change the number of threds based on your requirement.
threads   : 9
